model:
  _target_: multi_speaker_asr.models.whisper.Whisper
  model_name: CoRal-project/roest-v3-whisper-1.5b

evaluation:
  metrics:
    wer:
      _target_: torchmetrics.text.WordErrorRate
    cer:
      _target_: torchmetrics.text.CharErrorRate
    semdist: 
      _target_: multi_speaker_asr.utils.metrics.semDist
    ember:
      _target_: multi_speaker_asr.utils.metrics.embER 