device: 'cpu'
asr_filepath: 'src/hpc_results/exp_1/phase_1/asr_output_1.jsonl'
model_type: whisper
computetype: int4
cputhreads: 10
batch_size: 8
dataset_location: remote
dataset_mode: segments
backend_type: 'whisper.cpp'


use_saved_model: True
local_models_dir: 'src/multi_speaker_asr/models/saved_models/whisper/'
safe_tensors_filename: 'model.safetensors'
quantization_map_filename: 'quantization_map.json'


build_model: False