device: 'cpu'
asr_output_filename: 'asr_output_coral_segments_float32.jsonl'
align_output_filename: 'align_output_coral_segments_float32.jsonl'
final_output_filename: 'output_coral_segments_float32.jsonl'
model: 'pluttodk/roest-v3-whisper-1.5b-ct2'
data: 'coral'
computetype: float32
cputhreads: 4
alignment_model: 'CoRal-project/roest-v3-wav2vec2-315m'
hpc: True
loader_batchsize: 16
whisper_batchsize: 4