device: 'cpu'
asr_filepath: 'src/hpc_results/exp_1/phase_1/asr_output.jsonl'
model_type: wav2vec2
batch_size: 5
computetype: int8
dataset_location: remote
dataset_mode: segments
backend_type: torch

word_timestamps: True

use_saved_model: False
local_models_dir: 'src/multi_speaker_asr/models/saved_models/wav2vec/'
safe_tensors_filename: 'model.safetensors'
quantization_map_filename: 'quantization_map.json'

build_model: False