filepath: /root/master_thesis/thesis_multi_speaker_asr/results/diarization.jsonl
metadata: /root/master_thesis/thesis_multi_speaker_asr/data/coral-v3-long-form-conversations/test/coral_metadata.csv
batch_size: 1
device: 'cpu'
dataset_mode: recordings
diarization: True
build_model: False
dataset_location: local
