device: 'cpu'
asr_filepath: 'results\\wa_ct2_int8_sequential.jsonl'
model_type: 'whisper'
backend_type: 'ct2'
dataset_location: 'local'
metadata: 'L:\\Auditdata\\Wrist Angel - Video\\Amalie Sommer\\repo\\thesis_multi_speaker_asr\\data\\audio\\segments\\metadata_new.csv'
dataset_mode: 'segments'
batch_size: 1
computetype: int8
cputhreads: 6
intra_batched_inference: True
max_duration: !!float .inf

use_saved_model: False
local_models_dir: src\\multi_speaker_asr\\models\\saved_models\\wav2vec2\\
build_model: False
