device: 'cpu'
asr_filepath: 'results\\wa_whisper_cpp_int4.jsonl'
model_type: 'whisper'
backend_type: 'cpp'
dataset_location: 'local'
metadata: 'L:\\Auditdata\\Wrist Angel - Video\\Amalie Sommer\\repo\\thesis_multi_speaker_asr\\data\\audio\\segments\\metadata_new.csv'
dataset_mode: 'segments'
batch_size: 1
computetype: int8
cputhreads: 6
build_model: False
max_duration: 30
intra_batched_inference: False
